### ISSUE TITLE
Unable to skip the columns with -skipCols option

### ISSUE THREAD

**Issue by giri1504** [brianmhess/cassandra-loader#73]
I am unable to skip the columns while losing data with this cassandra loader  -skipCols option.Below is the command i am using and corresponding error getting with it.
Could you please help me with this issue fix.Also explain exact usage of it.
skipRows option is wrking fine.

$ ./cassandra-loader -f ~/inputfile.csv -host 127.0.0.1 -schema "ks1.skiptest(test1,test2,test3)" -skipCols 1
*** Processing skipprocessing.csv
Rows has different number of fields (3) than expected (4)
Error parsing line 1 in skipprocessing.csv: dpk,hyd,test
Rows has different number of fields (3) than expected (4)
Error parsing line 2 in skipprocessing.csv: rajan,chn,test
*** DONE: skipprocessing.csv  number of lines processed: 2 (0 inserted)
Lines Processed: 	-1  Rate: 	0.0

**Comment by brianmhess** [comment]
The -skipCols argument tells cassandra-loader to ignore the list of columns in that argument.  For example, if you had:
cassandra-loader -schema "ks1.skiptest(test1,test2,test3)" -skipCols 1
And your data was:
1,2,3,4
Then the first column (the value 1) would be skipped and test1 would get the value 2, test2 would get the value 3, and test 3 would get the value 4.
The parser will expect the number of columns to be 4, so that it can skip one and still have three to assign.  In general, the parser expects there to be #columns_in_the_schema + #skip_columns fields in the delimited file.
